//go:build windows

package app

import (
	"syscall"
	"unsafe"
)

// applyWindowIcon sets the running window's icon (title bar, taskbar, Alt-Tab)
// to the app icon embedded in the exe (resource ID 1 — see
// cmd/whatskept/rsrc_windows_amd64.syso, generated by `make winicon`).
//
// webview/WebView2 creates its window without assigning an icon, so without
// this the taskbar shows a generic glyph even though the exe's *file* icon (in
// Explorer) is correct — they're separate. Best-effort: any failure just
// leaves the default icon.
func applyWindowIcon(win unsafe.Pointer) {
	hwnd := uintptr(win)
	if hwnd == 0 {
		return
	}
	kernel32 := syscall.NewLazyDLL("kernel32.dll")
	user32 := syscall.NewLazyDLL("user32.dll")
	getModuleHandle := kernel32.NewProc("GetModuleHandleW")
	loadImage := user32.NewProc("LoadImageW")
	sendMessage := user32.NewProc("SendMessageW")

	hInst, _, _ := getModuleHandle.Call(0) // our own exe module

	const (
		imageIcon = 1      // IMAGE_ICON
		lrShared  = 0x8000 // LR_SHARED — system manages the handle's lifetime
		wmSetIcon = 0x0080 // WM_SETICON
		iconSmall = 0
		iconBig   = 1
		resIconID = 1 // matches `1 ICON ...` in build/icon.rc
	)

	// Big (32x32) drives the taskbar / Alt-Tab; small (16x16) the title bar.
	// LoadImageW selects the best-matching size from the embedded icon group.
	if hBig, _, _ := loadImage.Call(hInst, uintptr(resIconID), imageIcon, 32, 32, lrShared); hBig != 0 {
		sendMessage.Call(hwnd, wmSetIcon, iconBig, hBig)
	}
	if hSmall, _, _ := loadImage.Call(hInst, uintptr(resIconID), imageIcon, 16, 16, lrShared); hSmall != 0 {
		sendMessage.Call(hwnd, wmSetIcon, iconSmall, hSmall)
	}
}
